name: 'helm'
on:
  pull_request:
    branches: 
      - '*'
  push:
    branches:
      - master
jobs:
  lint:
    name: 'helm/lint'
    runs-on: ubuntu-latest
    env:
      CT_CHART_DIRS: ${chart_dir}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Helm Lint
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          command: lint
