on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: 'hugo/s3-deploy'
    runs-on: [${runner}]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: ${submodules}
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '${hugo_version}'

      - name: Build
        run: hugo --minify

      - name: Deploy
        run: |
          aws s3 sync ./public/ s3://${s3_bucket}${target_dir} --no-progress
%{ if length(environment) > 0 ~}
        env:
%{ for key, val in environment ~}
          ${key}: "${val}"
%{ endfor ~}
%{ endif ~}
