name: Terraform validate
on: push
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: ${terraform_dir}
        env:
          GITHUB_TOKEN: $${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: ${terraform_dir}
        env:
          GITHUB_TOKEN: $${{ secrets.GITHUB_TOKEN }}
