name: 'node'
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
  coveralls:
    needs: checkout
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ ${join(",", node_versions)} ]
    name: Node $${{ matrix.node }}
    steps:

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: $${{ matrix.node }}
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm run coverage
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v1.1.0
        with:
          github-token: $${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
