name: 'release/drafter'
on:
  push:
    branches:
      - master

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
